import Head from 'next/head'
import React from 'react';
import ColorPicker from '../components/ColorPicker';
import StyleEditor from '../components/StyleEditor';
import ThemeSelector from '../components/ThemeSelector';
import UpdateStyleComponent from '../components/UpdateStyleComponent';
import { ThemeProvider } from '../context/ThemeContext';
import { Inter } from 'next/font/google'
// @ts-ignore
import { Playground, store } from 'graphql-playground-react'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
          <ThemeProvider>
              <div>
                  <h1>Welcome to the Dynamic Styling Page</h1>
                  <ThemeSelector />
                  {/*<Playground endpoint='https://api.graph.cool/simple/v1/swapi' />*/}
                  <ColorPicker onColorChange={(color) => console.log(color)} />
                  <StyleEditor />
                  <UpdateStyleComponent />
              </div>
          </ThemeProvider>
      </main>
    </>
  )
}
